name = "eniaiyejuni-raphael/swiftfund"
version = "0.0.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'eniaiyejuni-raphael/swiftfund'"

[repository]
user = "eniaiyejuni-raphael"
project = "swiftfund-smartcontract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
